import {animals,sources,remainsSources} from './data.js';
const app=document.getElementById('app'), menu=document.getElementById('menu'),scrim=document.getElementById('scrim'),menuButton=document.getElementById('menuButton');
const sourceMap=new Map([...sources,...remainsSources].map(([id,title,url])=>[id,{title,url}]));
document.getElementById('menuAnimals').innerHTML=animals.map(a=>`<a href="/animal/${a.slug}" data-link>${a.name}</a>`).join('');
function setMenu(open){menu.classList.toggle('open',open);menu.inert=!open;scrim.hidden=!open;menuButton.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':'';if(open)document.getElementById('closeButton').focus();else menuButton.focus()}
menuButton.addEventListener('click',()=>setMenu(true));document.getElementById('closeButton').addEventListener('click',()=>setMenu(false));scrim.addEventListener('click',()=>setMenu(false));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.classList.contains('open'))setMenu(false)});
const image=a=>`<img src="/images/${a.image}.webp" width="1600" height="900" alt="שחזור אמנותי של ${a.name} בסביבתו" ${a.slug==='mammoth'?'':'loading="lazy"'}>`;
function home(){return `<section class="hero"><div class="hero-inner"><div class="eyebrow">מסע אל העולם הפלייסטוקני</div><h1>חיות עידן הקרח</h1><p>לפני אלפי שנים חיו ברחבי העולם יונקים גדולים שהותאמו לערבות קרות, לצד טורפים ומינים שחלקם שרדו עד היום.</p></div></section><div class="wrap"><p class="intro">״עידן הקרח״ הוא כינוי עממי לתקופות קרח רבות. כאן נתמקד בעיקר בפלייסטוקן המאוחר, ובבעלי החיים שחיו באזורי הערבה, ההרים והיערות בתקופה זו. האיורים הם שחזורים אמנותיים; ההסברים מציינים כשפרט מסוים אינו ידוע בוודאות.</p><h2 class="section-title">הכירו את בעלי החיים</h2><div class="grid">${animals.map(a=>`<a class="card" href="/animal/${a.slug}" data-link>${image(a)}<div class="card-content"><h3>${a.name}</h3><span class="latin" lang="la">${a.scientific}</span><p>${a.intro}</p><span class="pill">${a.status}</span></div></a>`).join('')}</div></div>`}
function topic(title,body){return `<section class="topic"><div class="topic-head"><h2>${title}</h2><button class="speak-button" type="button" aria-label="הקראת ${title}" aria-pressed="false">🔊 הקראה</button></div><div class="topic-body">${body}</div></section>`}
function detail(a){const refs=[...a.refs,...a.remainsRefs].map(id=>sourceMap.get(id)).filter(Boolean);return `<article class="wrap detail"><a class="back" href="/" data-link>← חזרה לכל בעלי החיים</a>${image(a)}<div class="detail-head"><span class="eyebrow">${a.group} · ${a.status}</span><h1>${a.name}</h1><span class="latin" lang="la">${a.scientific}</span><div class="meta"><span>תפוצה: ${a.range}</span><span>מצב: ${a.status}</span></div></div><div class="detail-layout"><div>${topic('מי היה בעל החיים הזה?',`<p>${a.intro}</p>`)}${topic('איך גילו אותו?',`<p>${a.discovery}</p>`)}${topic('מידות ומשקל',`<p>${a.dimensions}</p>`)}${topic('אילו שרידים נמצאו?',`<p>${a.remains}</p><div class="remains-refs"><strong>מקורות לשרידים:</strong> ${a.remainsRefs.map(id=>{const r=sourceMap.get(id);return `<a href="${r.url}" target="_blank" rel="noopener noreferrer">${r.title} ↗</a>`}).join('')}</div>`)}${topic('מה פירוש השם?',`<div class="term-list">${a.etym.map(([term,description])=>`<div class="term"><strong>${term}</strong><p>${description}</p></div>`).join('')}</div>`)}</div><aside class="aside">${topic('כדאי לדעת',`<p>${a.note}</p>`)}<h2>לקריאה נוספת</h2><ul class="ref-list">${refs.map(r=>`<li><a href="${r.url}" target="_blank" rel="noopener noreferrer">${r.title} ↗</a></li>`).join('')}</ul></aside></div></article>`}
function references(){return `<div class="wrap sources"><a class="back" href="/" data-link>← חזרה לעמוד הבית</a><h1>מקורות והערות</h1><p>המידע באתר מבוסס על פרסומי מוזיאוני טבע ומאמרים מדעיים. מקור לכל חיה מופיע גם בעמוד שלה. האטימולוגיה מפרידה בין השם העממי בעברית לבין חלקי השם המדעי; כשמקורו של רכיב אינו מוסכם, הדבר מצוין במפורש.</p><p>התמונות נוצרו במיוחד לאתר והן שחזורים אמנותיים, לא תצלומים או עדות מדעית למראה מדויק. צורות הגוף, דגמי פרווה וצבעים מסוימים הם השערות מבוססות במידות שונות.</p><ul>${[...sources,...remainsSources].map(([,title,url])=>`<li><a href="${url}" target="_blank" rel="noopener noreferrer">${title} ↗</a></li>`).join('')}</ul></div>`}
let activeSpeechButton=null;
function render(){stopSpeech();const path=decodeURI(location.pathname),a=animals.find(x=>path===`/animal/${x.slug}`);let title;if(path==='/'){app.innerHTML=home();title='חיות עידן הקרח'}else if(a){app.innerHTML=detail(a);title=`${a.name} | חיות עידן הקרח`}else if(path==='/sources'){app.innerHTML=references();title='מקורות | חיות עידן הקרח'}else{app.innerHTML=`<div class="wrap sources"><h1>העמוד לא נמצא</h1><a class="back" href="/" data-link>חזרה לעמוד הבית</a></div>`;title='העמוד לא נמצא | חיות עידן הקרח'}document.title=title;document.querySelectorAll('.drawer a').forEach(el=>{if(el.getAttribute('href')===path)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')})}
document.addEventListener('click',e=>{const a=e.target.closest('a[data-link]');if(!a||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();if(location.pathname!==a.pathname){history.pushState({},'',a.pathname);render();window.scrollTo(0,0)}if(menu.classList.contains('open'))setMenu(false)});window.addEventListener('popstate',render);render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js'));

function stopSpeech(){if('speechSynthesis' in window)window.speechSynthesis.cancel();if(activeSpeechButton){activeSpeechButton.textContent='🔊 הקראה';activeSpeechButton.setAttribute('aria-pressed','false');activeSpeechButton=null}}
document.addEventListener('click',event=>{const button=event.target.closest('.speak-button');if(!button)return;if(button===activeSpeechButton){stopSpeech();return}stopSpeech();if(!('speechSynthesis' in window)){button.textContent='הקראה אינה זמינה בדפדפן הזה';button.disabled=true;return}const section=button.closest('.topic');const spokenText=section.querySelector('.topic-body > p')?.innerText||section.querySelector('.topic-body').innerText;const message=new SpeechSynthesisUtterance(`${section.querySelector('h2').textContent}. ${spokenText}`);message.lang='he-IL';message.rate=.92;const voices=window.speechSynthesis.getVoices();message.voice=voices.find(v=>v.lang.toLowerCase()==='he-il')||voices.find(v=>v.lang.toLowerCase().startsWith('he'))||null;activeSpeechButton=button;button.textContent='■ עצירה';button.setAttribute('aria-pressed','true');message.onend=message.onerror=()=>{if(activeSpeechButton===button)stopSpeech()};window.speechSynthesis.speak(message)});
window.addEventListener('pagehide',stopSpeech);
