import {animals,sources} from './data.js';
const app=document.getElementById('app'), menu=document.getElementById('menu'),scrim=document.getElementById('scrim'),menuButton=document.getElementById('menuButton');
const sourceMap=new Map(sources.map(([id,title,url])=>[id,{title,url}]));
document.getElementById('menuAnimals').innerHTML=animals.map(a=>`<a href="/animal/${a.slug}" data-link>${a.name}</a>`).join('');
function setMenu(open){menu.classList.toggle('open',open);menu.inert=!open;scrim.hidden=!open;menuButton.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':'';if(open)document.getElementById('closeButton').focus();else menuButton.focus()}
menuButton.addEventListener('click',()=>setMenu(true));document.getElementById('closeButton').addEventListener('click',()=>setMenu(false));scrim.addEventListener('click',()=>setMenu(false));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.classList.contains('open'))setMenu(false)});
const image=a=>`<img src="/images/${a.image}.webp" width="1600" height="900" alt="שחזור אמנותי של ${a.name} בסביבתו" ${a.slug==='mammoth'?'':'loading="lazy"'}>`;
function home(){return `<section class="hero"><div class="hero-inner"><div class="eyebrow">מסע אל העולם הפלייסטוקני</div><h1>חיות עידן הקרח</h1><p>לפני אלפי שנים חיו ברחבי העולם יונקים גדולים שהותאמו לערבות קרות, לצד טורפים ומינים שחלקם שרדו עד היום.</p></div></section><div class="wrap"><p class="intro">״עידן הקרח״ הוא כינוי עממי לתקופות קרח רבות. כאן נתמקד בעיקר בפלייסטוקן המאוחר, ובבעלי החיים שחיו באזורי הערבה, ההרים והיערות בתקופה זו. האיורים הם שחזורים אמנותיים; ההסברים מציינים כשפרט מסוים אינו ידוע בוודאות.</p><h2 class="section-title">הכירו את בעלי החיים</h2><div class="grid">${animals.map(a=>`<a class="card" href="/animal/${a.slug}" data-link>${image(a)}<div class="card-content"><h3>${a.name}</h3><span class="latin" lang="la">${a.scientific}</span><p>${a.intro}</p><span class="pill">${a.status}</span></div></a>`).join('')}</div></div>`}
function detail(a){const refs=a.refs.map(id=>sourceMap.get(id)).filter(Boolean);return `<article class="wrap detail"><a class="back" href="/" data-link>← חזרה לכל בעלי החיים</a>${image(a)}<div class="detail-head"><span class="eyebrow">${a.group} · ${a.status}</span><h1>${a.name}</h1><span class="latin" lang="la">${a.scientific}</span><div class="meta"><span>תפוצה: ${a.range}</span><span>מצב: ${a.status}</span></div></div><div class="detail-layout"><div><h2>מי היה בעל החיים הזה?</h2><p>${a.intro}</p><h2>מה פירוש השם?</h2><div class="term-list">${a.etym.map(([term,description])=>`<div class="term"><strong>${term}</strong><p>${description}</p></div>`).join('')}</div></div><aside class="aside"><h2>כדאי לדעת</h2><p>${a.note}</p><h2>לקריאה נוספת</h2><ul class="ref-list">${refs.map(r=>`<li><a href="${r.url}" target="_blank" rel="noopener noreferrer">${r.title} ↗</a></li>`).join('')}</ul></aside></div></article>`}
function references(){return `<div class="wrap sources"><a class="back" href="/" data-link>← חזרה לעמוד הבית</a><h1>מקורות והערות</h1><p>המידע באתר מבוסס על פרסומי מוזיאוני טבע ומאמרים מדעיים. מקור לכל חיה מופיע גם בעמוד שלה. האטימולוגיה מפרידה בין השם העממי בעברית לבין חלקי השם המדעי; כשמקורו של רכיב אינו מוסכם, הדבר מצוין במפורש.</p><p>התמונות נוצרו במיוחד לאתר והן שחזורים אמנותיים, לא תצלומים או עדות מדעית למראה מדויק. צורות הגוף, דגמי פרווה וצבעים מסוימים הם השערות מבוססות במידות שונות.</p><ul>${sources.map(([,title,url])=>`<li><a href="${url}" target="_blank" rel="noopener noreferrer">${title} ↗</a></li>`).join('')}</ul></div>`}
function render(){const path=decodeURI(location.pathname),a=animals.find(x=>path===`/animal/${x.slug}`);let title;if(path==='/'){app.innerHTML=home();title='חיות עידן הקרח'}else if(a){app.innerHTML=detail(a);title=`${a.name} | חיות עידן הקרח`}else if(path==='/sources'){app.innerHTML=references();title='מקורות | חיות עידן הקרח'}else{app.innerHTML=`<div class="wrap sources"><h1>העמוד לא נמצא</h1><a class="back" href="/" data-link>חזרה לעמוד הבית</a></div>`;title='העמוד לא נמצא | חיות עידן הקרח'}document.title=title;document.querySelectorAll('.drawer a').forEach(el=>{if(el.getAttribute('href')===path)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')})}
document.addEventListener('click',e=>{const a=e.target.closest('a[data-link]');if(!a||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();if(location.pathname!==a.pathname){history.pushState({},'',a.pathname);render();window.scrollTo(0,0)}if(menu.classList.contains('open'))setMenu(false)});window.addEventListener('popstate',render);render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js'));
